apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kube-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube
  template:
    metadata:
      labels:
        app: kube
    spec:
      containers:
        - name: kube-container
          image: prashant0701/kube
          readinessProbe:
            exec:
              command:
              - ls
              - /var/ready