apiVersion: v1
kind: Pod
metadata:
  name: kube-liveliness
spec:
  containers:
    - image: prashant0701/kube-unhealthy
      name: kube-container
      livenessProbe:
        httpGet:
        path: /
        port: 8080
      ports:
        - containerPort: 8080
          protocol: TCP