apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-storageclass
spec:
  storageClassName: fast    # This PVC requests the custom storage class.
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce